name: Weekly Problem Check

on:
  schedule:
    - cron: "23 14 * * 4" # 매주 목요일 오후 11시 22분에 실행 (UTC 기준 14:22, 한국 시간으로 오후 11시 22분)
  workflow_dispatch: # 수동 실행을 위한 옵션

jobs:
  check-problems:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip   
          pip install PyGithub pytz
      - name: Run weekly check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .github/scripts/weekly_check.py
